export const REQUEST_DATABASE: string = 'REQUEST_DATABASE';
export const REQUEST_DATABASE_SET: string = 'REQUEST_DATABASE_SET';
export const REQUEST_PERSON: string = 'REQUEST_PERSON';
export const REQUEST_PERSON_SET: string = 'REQUEST_PERSON_SET';
export const REQUEST_MESSAGE: string = 'REQUEST_MESSAGE';
export const REQUEST_LISTENER: string = 'REQUEST_LISTENER';
export const REQUEST_LISTENER_SET: string = 'REQUEST_LISTENER_SET';
