export const REQUEST_DATABASE = 'REQUEST_DATABASE'
export const REQUEST_DATABASE_SET = 'REQUEST_DATABASE_SET'
export const REQUEST_PERSON = 'REQUEST_PERSON';
export const REQUEST_PERSON_SET = 'REQUEST_PERSON_SET';
export const REQUEST_MESSAGE = 'REQUEST_MESSAGE';
export const REQUEST_LISTENER = 'REQUEST_LISTENER';
export const REQUEST_LISTENER_SET = 'REQUEST_LISTENER_SET';