export const REQUEST_CHATROOMS = 'REQUEST_CHATROOMS'
export const REQUEST_CHATROOMS_SET = 'REQUEST_CHATROOMS_SET'

export const REQUEST_CLIENT = 'REQUEST_CLIENT';
export const REQUEST_CLIENT_SET = 'REQUEST_CLIENT_SET';

export const REQUEST_QUEUE = 'REQUEST_QUEUE';
export const REQUEST_QUEUE_SET = 'REQUEST_QUEUE_SET';

export const REQUEST_PERSON = 'REQUEST_PERSON';
export const REQUEST_PERSON_SET = 'REQUEST_PERSON_SET';

export const REQUEST_MESSAGE = 'REQUEST_MESSAGE';
